login: &login
  adapter: postgresql
  username: <%=ENV["WRONG_DB_USER"] %>
  password: <%= ENV["WRONG_DB_PASSWORD"] %>
  host: localhost

boiler: &boiler
  adapter: postgresql
  encoding: unicode
  pool: 2


development:
  <<: *login
  <<: *boiler
  database: <%=ENV["WRONG_DB_NAME"] %>

